name: feature_dragster
version: 0.0.1-dev
description: Drag and Drop UI
homepage: https://github.com/core9/feature-dragster
environment:
  sdk: '>=0.6.17'
dependencies:
  browser: any
  dice: any
  hop: any
  html5lib: any
  js: any
  json_object: any
  lawndart: any
